
START TRANSACTION;

DROP TABLE IF EXISTS alterno;
DROP TABLE IF EXISTS barner;
DROP TABLE IF EXISTS boletin;
DROP TABLE IF EXISTS carnet;
DROP TABLE IF EXISTS cobros;
DROP TABLE IF EXISTS cobros_especiales;
DROP TABLE IF EXISTS comentarios;
DROP TABLE IF EXISTS datos;
DROP TABLE IF EXISTS dimension;
DROP TABLE IF EXISTS estudiante_evaluacion;
DROP TABLE IF EXISTS evaluacion;
DROP TABLE IF EXISTS eventos;
DROP TABLE IF EXISTS factura;
DROP TABLE IF EXISTS factura_detalle;
DROP TABLE IF EXISTS grado;
DROP TABLE IF EXISTS horario;
DROP TABLE IF EXISTS indicador;
DROP TABLE IF EXISTS mensajeria;
DROP TABLE IF EXISTS mural;
DROP TABLE IF EXISTS opciones;
DROP TABLE IF EXISTS outin;
DROP TABLE IF EXISTS pagos;
DROP TABLE IF EXISTS pregunta;
DROP TABLE IF EXISTS publicaciones;
DROP TABLE IF EXISTS respuesta;
DROP TABLE IF EXISTS sancion;
DROP TABLE IF EXISTS tipo_nota;
DROP TABLE IF EXISTS tips;
DROP TABLE IF EXISTS utiles;
DROP TABLE IF EXISTS votacion;
DROP TABLE IF EXISTS votacion_candidatos;
DROP TABLE IF EXISTS votacion_curso;
DROP TABLE IF EXISTS votacion_estudiante;

COMMIT;

